services:
  - postgresql
  - mysql
language: php
php:
- 5.5
- 5.6
- 7.0
install:
- phpenv rehash
- composer self-update
- composer require satooshi/php-coveralls "^1.0" --no-update --dev --prefer-dist
- composer install

before_script:
- psql -c 'create database sqlbuilder;' -U postgres
- mysql -e 'create database sqlbuilder;'

script:
- phpunit -c phpunit.travis-ci.xml

after_success:
- php vendor/bin/coveralls -v

cache:
- vendor
